### ISSUE TITLE
feature setRow() and setColumn()

### ISSUE THREAD

**Issue by Delapouite** [andrejewski/matt#1]
Hi Chris

Thanks for this library!

What about adding the following functions : 

``` js
setRow(row Number, elements [Any]) Matrix
setColumn(col Number, elements [Any]) Matrix
```

That would be really handy, currently I rely on .map() to do these simple operations.

**Comment by andrejewski** [comment]
Yes, I don't see why not since Matt already has `getRow` and `getColumn`. Their setter compliments make sense. If someone submits a pull and tests I'll accept it. I'm busy this week, but maybe next week I will have time to implement.

**Comment by andrejewski** [comment]
Added by pull request #2, thanks Bruno!

**Comment by Delapouite** [comment]
Thanks! Could you publish the new version on NPM?

**Comment by andrejewski** [comment]
It's available now, thanks for reminding me.
